import { useCallback, useEffect, useState } from 'react'
import { BriefcaseBusiness, Pencil, Plus, X } from 'lucide-react'
import { useStaffAuth } from '../auth/staffAuth'
import { EmptyState, ErrorMessage, LoadingState, PageHeader, Panel, StatusBadge, SuccessMessage } from '../components/AdminUi'
import { api } from '../lib/api'

const blank = { freelancerId: '', title: '', description: '', department: '', date: '', startTime: '09:00', endTime: '17:00', location: '', notes: '' }
const nextStatus = { assigned: 'accepted', accepted: 'in-progress', 'in-progress': 'completed' }

export default function FreelancerAssignments() {
  const { actor } = useStaffAuth()
  const ownerMode = actor?.role === 'freelancer'
  const [items, setItems] = useState([])
  const [staff, setStaff] = useState([])
  const [editor, setEditor] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { if (ownerMode) setItems(await api.getMyAssignments()); else { const [data, staffData] = await Promise.all([api.getAssignments({ limit: 200 }), api.getStaff({ role: 'freelancer', status: 'active', limit: 200 })]); setItems(data.data || []); setStaff(staffData.data || []) } } catch (loadError) { setError(loadError.message) } finally { setLoading(false) } }, [ownerMode])
  useEffect(() => { const timeout = window.setTimeout(load, 0); return () => window.clearTimeout(timeout) }, [load])
  async function save(form) { try { const response = form._id ? await api.updateAssignment(form._id, form) : await api.createAssignment(form); setEditor(null); setNotice(response.message); await load() } catch (saveError) { setError(saveError.message); throw saveError } }
  async function changeStatus(item, status) { try { const response = await api.updateAssignmentStatus(item._id, status); setNotice(response.message); await load() } catch (updateError) { setError(updateError.message) } }
  return <main className="admin-page min-h-screen px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><PageHeader title={ownerMode ? 'My Assignments' : 'Freelancer Assignments'} subtitle={ownerMode ? 'Accept assigned work, begin delivery, and mark it complete.' : 'Assign scoped operational work to active freelancers.'} actions={!ownerMode && <button type="button" onClick={() => setEditor({ ...blank })} className="inline-flex h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white"><Plus size={16} /> New assignment</button>} /><ErrorMessage message={error} /><SuccessMessage message={notice} /><Panel>{loading ? <LoadingState /> : !items.length ? <EmptyState label="No freelancer assignments found." /> : <div className="grid gap-4 p-5 lg:grid-cols-2">{items.map((item) => <article key={item._id} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><BriefcaseBusiness size={19} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-extrabold text-slate-900">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{item.department} · {item.date} · {item.startTime}–{item.endTime}</p></div><StatusBadge value={item.status} /></div>{!ownerMode && <p className="mt-3 text-sm font-bold text-emerald-700">{item.freelancerId?.name || 'Unknown freelancer'}</p>}<p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p>{item.location && <p className="mt-2 text-xs font-semibold text-slate-400">Location: {item.location}</p>}<div className="mt-4 flex flex-wrap gap-2">{ownerMode && nextStatus[item.status] && <button type="button" onClick={() => changeStatus(item, nextStatus[item.status])} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Mark {pretty(nextStatus[item.status])}</button>}{!ownerMode && <><button type="button" onClick={() => setEditor(toForm(item))} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold"><Pencil size={14} /> Edit</button>{!['completed','cancelled'].includes(item.status) && <button type="button" onClick={() => changeStatus(item, 'cancelled')} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">Cancel</button>}</>}</div></div></div></article>)}</div>}</Panel>{editor && <AssignmentEditor value={editor} staff={staff} onClose={() => setEditor(null)} onSave={save} />}</div></main>
}

function AssignmentEditor({ value, staff, onClose, onSave }) {
  const [form, setForm] = useState(value)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  function update(event) { const { name, value: next } = event.target; setForm((current) => ({ ...current, [name]: next })) }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { await onSave(form) } catch (saveError) { setError(saveError.message) } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-[100] grid place-items-center p-4"><button type="button" onClick={onClose} className="absolute inset-0 bg-slate-950/50" aria-label="Close" /><form onSubmit={submit} className="relative flex max-h-[94vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Freelancer work order</p><h2 className="mt-1 text-xl font-extrabold">{form._id ? 'Edit assignment' : 'New assignment'}</h2></div><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border"><X size={18} /></button></header><div className="grid gap-4 overflow-y-auto p-5 sm:grid-cols-2">{error && <p className="sm:col-span-2 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</p>}<Field label="Freelancer"><select name="freelancerId" value={form.freelancerId} onChange={update} required className="control"><option value="">Choose freelancer</option>{staff.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Title"><input name="title" value={form.title} onChange={update} required className="control" /></Field><Field label="Department"><input name="department" value={form.department} onChange={update} required className="control" /></Field><Field label="Date"><input name="date" type="date" value={form.date} onChange={update} required className="control" /></Field><Field label="Start"><input name="startTime" type="time" value={form.startTime} onChange={update} required className="control" /></Field><Field label="End"><input name="endTime" type="time" value={form.endTime} onChange={update} required className="control" /></Field><Field label="Location"><input name="location" value={form.location} onChange={update} className="control" /></Field><label className="sm:col-span-2"><span className="label">Description</span><textarea name="description" value={form.description} onChange={update} rows="5" required className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm" /></label><label className="sm:col-span-2"><span className="label">Notes</span><textarea name="notes" value={form.notes} onChange={update} rows="2" className="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm" /></label></div><footer className="flex justify-end gap-2 border-t bg-slate-50 p-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border bg-white px-4 text-sm font-bold">Cancel</button><button disabled={saving} className="h-10 rounded-xl bg-emerald-700 px-5 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Saving...' : 'Save assignment'}</button></footer></form></div>
}

function Field({ label, children }) { return <label><span className="label">{label}</span>{children}</label> }
function pretty(value) { return String(value || '').split('-').map((part) => part && part[0].toUpperCase() + part.slice(1)).join(' ') }
function toForm(item) { return { ...item, freelancerId: item.freelancerId?._id || item.freelancerId } }
